<html>
  <head>
    <title>{{pageInfo.headerInfo.title}}</title>
  </head>
  <body>
    <h3>{{pageInfo.contentHtml}}</h3>
    <div>
        <button>{{pageInfo.buttonInfo[0].text}}</button>
    </div>
  </body>
</html>